### ISSUE TITLE
Source and target as params

### ISSUE THREAD

**Issue by ghost** [rendon/tli#2]
The source and target aren't being validated when the `tli` command is invoked from the command line.

Example:

```
    $ tli --source en --target whatever
    > 
```

It is clearly a bad request (`whatever` isn't a valid language), however `tli` behavior just get the user in the interactive mode --maybe the user wanted to translate the `whatever` expression to its native language--.

So IMO `tli` should  validate the source and target and responds with an error message when any of them are invalid.

**Comment by rendon** [comment]
> maybe the user wanted to translate the whatever expression to its native language

That's not the case because _whatever_ is preceded by `--target`. However, you're right, **tli** should report that to the user before entering interactive mode.
